### ISSUE TITLE
"more than x" language is unclear

### ISSUE THREAD

**Issue by deathsythe47** [Avygeil/JKASteamBot#3]
`- threshold: 0-32 (you will automatically be notified once if the amount of players on the server is past the threshold)`

`You will be notified once there are more than x players connected.`

These messages are unclear as to whether it is **greater than** or **greater than or equal to**. For example, if I set my `threshold` to `1`, I don't know if I will be messaged when there are 2 players on the server, or when there is 1 player on the server. Could rewrite to be more clear.

**Comment by Avygeil** [comment]
This was already fixed on my local repo
