### ISSUE TITLE
Use of line breaks before first part of message is inconsistent

### ISSUE THREAD

**Issue by deathsythe47** [Avygeil/JKASteamBot#5]
Since you are obviously stuck with Steam putting `3:54 PM - [BOT] Elysium [0/14+2]:` at the beginning of the first line, it's nice to add a line break before the first message you send.

This is correctly done with `!help`, which gives the result:
```
4:00 PM - [BOT] Elysium [0/14+2]: 
- !help: shows this message
- !status: lists the players currently on the server and the map
- !config: configure the way you receive notifications (use !config usage for help)
```

(notice the line break after `3:54 PM - [BOT] Elysium [0/14+2]:` before it tells me stuff)

However, with some messages, this line break is not added. For example, when I do `!status` I get:
```
4:00 PM - [BOT] Elysium [0/14+2]: The server is empty.
Current map: mp/siege_hoth2
```

Notice that there is no line break after `4:00 PM - [BOT] Elysium [0/14+2]:`

IMO there should always be a line break.

**Comment by Avygeil** [comment]
i just forgot to put it everywhere

**Comment by Avygeil** [comment]
4ea25fb510c258435afe49625c87f8785596e702
Although it only consistently sends it for multi line messages instead. I don't think it should add a line break to say short messages.
